import type { CategoryNode } from '@/types/category';

export const DEFAULT_CATEGORIES: CategoryNode[] = [
  {
    id: 'food',
    label: 'Alimentación',
    color: '#FF6B35',
    emoji: '🍔',
    children: [
      { id: 'food-supermarket', label: 'Supermercado', parentId: 'food', color: '#FF6B35', emoji: '🛒' },
      { id: 'food-restaurant', label: 'Restaurantes', parentId: 'food', color: '#FF6B35', emoji: '🍽️' },
      { id: 'food-cafe', label: 'Cafés', parentId: 'food', color: '#FF6B35', emoji: '☕' },
      { id: 'food-fastfood', label: 'Comida rápida', parentId: 'food', color: '#FF6B35', emoji: '🍕' },
      { id: 'food-drinks', label: 'Bebidas', parentId: 'food', color: '#FF6B35', emoji: '🥤' },
    ],
  },
  {
    id: 'transport',
    label: 'Transporte',
    color: '#4ECDC4',
    emoji: '🚗',
    children: [
      { id: 'transport-gas', label: 'Gasolina', parentId: 'transport', color: '#4ECDC4', emoji: '⛽' },
      { id: 'transport-public', label: 'Transporte público', parentId: 'transport', color: '#4ECDC4', emoji: '🚌' },
      { id: 'transport-taxi', label: 'Taxi/Uber', parentId: 'transport', color: '#4ECDC4', emoji: '🚕' },
      { id: 'transport-maintenance', label: 'Mantenimiento', parentId: 'transport', color: '#4ECDC4', emoji: '🔧' },
      { id: 'transport-parking', label: 'Estacionamiento', parentId: 'transport', color: '#4ECDC4', emoji: '🅿️' },
    ],
  },
  {
    id: 'housing',
    label: 'Vivienda',
    color: '#45B7D1',
    emoji: '🏠',
    children: [
      { id: 'housing-rent', label: 'Alquiler', parentId: 'housing', color: '#45B7D1', emoji: '🏠' },
      { id: 'housing-mortgage', label: 'Hipoteca', parentId: 'housing', color: '#45B7D1', emoji: '🏦' },
      { id: 'housing-utilities', label: 'Servicios básicos', parentId: 'housing', color: '#45B7D1', emoji: '💡' },
      { id: 'housing-internet', label: 'Internet', parentId: 'housing', color: '#45B7D1', emoji: '📶' },
      { id: 'housing-cleaning', label: 'Limpieza', parentId: 'housing', color: '#45B7D1', emoji: '🧹' },
    ],
  },
  {
    id: 'entertainment',
    label: 'Entretenimiento',
    color: '#A855F7',
    emoji: '🎬',
    children: [
      { id: 'entertainment-streaming', label: 'Streaming', parentId: 'entertainment', color: '#A855F7', emoji: '📺' },
      { id: 'entertainment-cinema', label: 'Cine', parentId: 'entertainment', color: '#A855F7', emoji: '🎬' },
      { id: 'entertainment-games', label: 'Videojuegos', parentId: 'entertainment', color: '#A855F7', emoji: '🎮' },
      { id: 'entertainment-music', label: 'Música', parentId: 'entertainment', color: '#A855F7', emoji: '🎵' },
      { id: 'entertainment-sports', label: 'Deportes', parentId: 'entertainment', color: '#A855F7', emoji: '⚽' },
    ],
  },
  {
    id: 'health',
    label: 'Salud',
    color: '#22C55E',
    emoji: '💊',
    children: [
      { id: 'health-doctor', label: 'Médico', parentId: 'health', color: '#22C55E', emoji: '👨‍⚕️' },
      { id: 'health-pharmacy', label: 'Farmacia', parentId: 'health', color: '#22C55E', emoji: '💊' },
      { id: 'health-gym', label: 'Gym', parentId: 'health', color: '#22C55E', emoji: '💪' },
      { id: 'health-psychology', label: 'Psicología', parentId: 'health', color: '#22C55E', emoji: '🧠' },
      { id: 'health-dental', label: 'Dental', parentId: 'health', color: '#22C55E', emoji: '🦷' },
    ],
  },
  {
    id: 'education',
    label: 'Educación',
    color: '#F59E0B',
    emoji: '📚',
    children: [
      { id: 'education-courses', label: 'Cursos', parentId: 'education', color: '#F59E0B', emoji: '💻' },
      { id: 'education-books', label: 'Libros', parentId: 'education', color: '#F59E0B', emoji: '📖' },
      { id: 'education-university', label: 'Universidad', parentId: 'education', color: '#F59E0B', emoji: '🎓' },
      { id: 'education-materials', label: 'Materiales', parentId: 'education', color: '#F59E0B', emoji: '📝' },
      { id: 'education-languages', label: 'Idiomas', parentId: 'education', color: '#F59E0B', emoji: '🌍' },
    ],
  },
  {
    id: 'shopping',
    label: 'Compras',
    color: '#EC4899',
    emoji: '🛍️',
    children: [
      { id: 'shopping-clothes', label: 'Ropa', parentId: 'shopping', color: '#EC4899', emoji: '👗' },
      { id: 'shopping-electronics', label: 'Electrónica', parentId: 'shopping', color: '#EC4899', emoji: '📱' },
      { id: 'shopping-home', label: 'Hogar', parentId: 'shopping', color: '#EC4899', emoji: '🛋️' },
      { id: 'shopping-beauty', label: 'Belleza', parentId: 'shopping', color: '#EC4899', emoji: '💄' },
      { id: 'shopping-accessories', label: 'Accesorios', parentId: 'shopping', color: '#EC4899', emoji: '👜' },
    ],
  },
  {
    id: 'services',
    label: 'Servicios',
    color: '#6366F1',
    emoji: '📱',
    children: [
      { id: 'services-phone', label: 'Teléfono', parentId: 'services', color: '#6366F1', emoji: '📞' },
      { id: 'services-subscriptions', label: 'Suscripciones', parentId: 'services', color: '#6366F1', emoji: '🔄' },
      { id: 'services-insurance', label: 'Seguros', parentId: 'services', color: '#6366F1', emoji: '🛡️' },
      { id: 'services-bank', label: 'Banco', parentId: 'services', color: '#6366F1', emoji: '🏦' },
      { id: 'services-memberships', label: 'Membresías', parentId: 'services', color: '#6366F1', emoji: '🎟️' },
    ],
  },
  {
    id: 'investments',
    label: 'Inversiones',
    color: '#10B981',
    emoji: '📈',
    children: [
      { id: 'investments-stocks', label: 'Acciones', parentId: 'investments', color: '#10B981', emoji: '📊' },
      { id: 'investments-crypto', label: 'Cripto', parentId: 'investments', color: '#10B981', emoji: '₿' },
      { id: 'investments-funds', label: 'Fondos', parentId: 'investments', color: '#10B981', emoji: '💹' },
      { id: 'investments-realestate', label: 'Bienes raíces', parentId: 'investments', color: '#10B981', emoji: '🏗️' },
      { id: 'investments-savings', label: 'Ahorros', parentId: 'investments', color: '#10B981', emoji: '🏦' },
    ],
  },
  {
    id: 'income',
    label: 'Ingresos',
    color: '#3B82F6',
    emoji: '💰',
    children: [
      { id: 'income-salary', label: 'Salario', parentId: 'income', color: '#3B82F6', emoji: '💼' },
      { id: 'income-freelance', label: 'Freelance', parentId: 'income', color: '#3B82F6', emoji: '💻' },
      { id: 'income-rentals', label: 'Alquileres', parentId: 'income', color: '#3B82F6', emoji: '🏠' },
      { id: 'income-dividends', label: 'Dividendos', parentId: 'income', color: '#3B82F6', emoji: '📈' },
      { id: 'income-other', label: 'Otros', parentId: 'income', color: '#3B82F6', emoji: '🎁' },
    ],
  },
];
